### ISSUE TITLE
Cursor disappears when triggering plugin

### ISSUE THREAD

**Issue by mawkler** [gukz/ftFT.nvim#5]
Awesome plugin! I've been using [quick-scope](https://github.com/unblevable/quick-scope) for quite a while and am now trying this plugin out. Something I immediately noticed is that the cursor disappears when triggering this plugin (i.e. when I for instance press `t`) until I press the character to jump to. This happen in quick-scope.

**Comment by gukz** [comment]
Hi @Melkster , so I guess you want to report an issue that the cursor disappears when pressing f/t/F/T, right?
If that's the case, can you describe in more detail why that's a problem?
thanks

**Comment by mawkler** [comment]
To me personally it's distracting. Since the default `f`/`t`/`F`/`T` don't behave that way I would say that it is an undesired behaviour :)

**Comment by gukz** [comment]
@mawkler Hi, would you please upgrade to the latest version of ftFT.nvim? I have made some fix to this issue, feedback is welcome!

**Comment by mawkler** [comment]
@gukz Seems to have solved the issue, thank you very much!
