### ISSUE TITLE
How to use? Add more explanations in README

### ISSUE THREAD

**Issue by cpkio** [gukz/ftFT.nvim#8]
Probably some more explanations needed.
![2022-01-18_112227](https://user-images.githubusercontent.com/1917113/149898534-76af3fc7-d60d-4e11-9b5c-a90ba47880b4.png)

This is what I see. What are these numbers and why are there so many `<`s?

**Comment by gukz** [comment]
Hi @cpkio, can you provide your nvim version and your OS version? thanks

**Comment by cpkio** [comment]
Im'm using Nvim 0.5.1 on Windows 10 x64. The text is UTF8 cyrillics.

**Comment by gukz** [comment]
Hi @cpkio  sorry for replying so late, I cannot repro this in my machine (win 11 x64), so would you please post that file to me? so I can test it locally.

**Comment by cpkio** [comment]
I think this should be enough.
```
Над таблицей «Участки недропользования» расположены кнопки :button:`Создать`,
:button:`Удалить`, :button:`Редактировать`, :button:`Просмотр`,
:button:`Экспорт в csv` и :button:`Показать на карте`. Описание функций этих
кнопок указано в таблице :link:`Кнопки работы с записями таблицы «Участки недропользования»`.
```

**Comment by gukz** [comment]
thanks, @cpkio, I repro this now!
looks the `<` are characters left angle brackets (e.g. `<b2>`), current code can handle ASCII content well but not all the UTF-8 characters, I will start to solve this problem and post a fix for it ASAP.
thanks for reporting this bug.

**Comment by gukz** [comment]
@cpkio I have fixed this issue, can you try the latest version?
